---
- name: Export config as code info from AWX, AAP, or Ascender
  hosts: save-files
  gather_facts: false
  vars:
    export_objects: 
#      - applications
#      - credentials
#      - credential_types
#      - execution_environments
#      - inventory
#      - inventory_sources
#      - job_templates
#      - notification_templates
#      - organizations
#      - projects
#      - schedules
#      - teams
      - users
#      - workflow_job_templates
  
  environment:
    CONTROLLER_HOST: "https://{{ export_host }}"
    CONTROLLER_USERNAME: "{{ gen1_user }}"
    CONTROLLER_PASSWORD: "{{ gen1_pword }}"
    CONTROLLER_VERIFY_SSL: False
  tasks:
  - name: Create temp file directory
    ansible.builtin.file:
      path: /tmp/export_files
      state: directory
      mode: '0755'
    delegate_to: localhost

  - name: Create temp file directory
    ansible.builtin.file:
      path: /tmp/export_files
      state: directory
      mode: '0755'

  - name: create all of the export files from template file
    ansible.builtin.template:
      src: export_template.yml.j2
      dest: "{{ playbook_dir }}/export_{{ item }}.yml"
    loop: "{{ export_objects }}"
    delegate_to: localhost
    
  - name: Export objects loop.  Loop through list and export those categories.
    ansible.builtin.include_tasks:
      file: "export_{{ item }}.yml"
    loop: "{{ export_objects }}"
