---
- name: Export config as code info from AWX, AAP, or Ascender
  hosts: localhost
  gather_facts: false
  vars:
  environment:
    CONTROLLER_HOST: "https://{{ export_host }}"
    CONTROLLER_USERNAME: "{{ gen1_user }}"
    CONTROLLER_PASSWORD: "{{ gen1_pword }}"
    CONTROLLER_VERIFY_SSL: False
  tasks:
  - name: Export all inventories
    awx.awx.export:
      inventory: 'all'
      # inventory: 'Demo Inventory'
    register: inventory_export

  - name: Debug inventory_export
    ansible.builtin.debug:
      # var: inventory_export | to_nice_yaml( width=50, explicit_start=True, explicit_end=True)
      var: inventory_export
