---
- name: Export config as code info from AWX, AAP, or Ascender
  #hosts: save-files
  hosts: localhost
  gather_facts: false
  vars:
    controller_configuration_inventories_enforce_defaults: true
  
    export_objects: 
#      - applications
#      - credentials
#      - credential_types
#      - execution_environments
      - inventory
#      - inventory_sources
#      - job_templates
#      - notification_templates
#      - organizations
#      - projects
#      - schedules
#      - teams
#      - users
#      - workflow_job_templates
  
  environment:
    CONTROLLER_HOST: "https://{{ import_host }}"
    CONTROLLER_USERNAME: "{{ gen2_user }}"
    CONTROLLER_PASSWORD: "{{ gen2_pword }}"
    CONTROLLER_VERIFY_SSL: False

  tasks:
  - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
    ansible.builtin.include_vars:
      # file: inventory.yml
      dir: configs
      
#  - name: debug inventory
#    ansible.builtin.debug:
#      # var: inventory.variables
#      var: inventory

  - name: Add invnetory
    when: item == "inventory"
    ansible.builtin.include_role:
      # name: infra.controller_configuration.inventories
      name: inventories
    loop: "{{ export_objects }}"
