

    credential_types:
    -   description: ''
        injectors:
            extra_vars:
                gen1_pword: '{{ supp_gen1_pword }}'
                gen1_user: '{{ supp_gen1_user }}'
        inputs:
            fields:
            -   id: supp_gen1_user
                label: Username
                type: string
            -   id: supp_gen1_pword
                label: Password
                secret: true
                type: string
            required:
            - supp_gen1_user
            - supp_gen1_pword
        kind: cloud
        name: generic credential 1
        natural_key:
            kind: cloud
            name: generic credential 1
            type: credential_type
    -   description: ''
        injectors:
            extra_vars:
                gen2_pword: '{{ supp_gen2_pword }}'
                gen2_user: '{{ supp_gen2_user }}'
        inputs:
            fields:
            -   id: supp_gen2_user
                label: Username
                type: string
            -   id: supp_gen2_pword
                label: Password
                secret: true
                type: string
            required:
            - supp_gen2_user
            - supp_gen2_pword
        kind: cloud
        name: generic credential 2
        natural_key:
            kind: cloud
            name: generic credential 2
            type: credential_type
    -   description: ''
        injectors:
            extra_vars:
                mtn_access_key: '{{ supp_mtn_access_key }}'
        inputs:
            fields:
            -   id: supp_mtn_access_key
                label: Mountain Access Key
                secret: true
                type: string
            required:
            - supp_mtn_access_key
        kind: cloud
        name: Mountain Access Key
        natural_key:
            kind: cloud
            name: Mountain Access Key
            type: credential_type
    -   description: ''
        injectors:
            extra_vars:
                cert_key: '{{ supp_cert_key }}'
        inputs:
            fields:
            -   id: supp_cert_key
                label: Certificate Key
                multiline: true
                secret: true
                type: string
            required:
            - supp_cert_key
        kind: cloud
        name: SSH Certificate Key
        natural_key:
            kind: cloud
            name: SSH Certificate Key
            type: credential_type


...