

    credentials:
    -   credential_type:
            kind: cloud
            name: generic credential 1
            type: credential_type
        description: ''
        inputs:
            supp_gen1_user: admin
        name: Ascender Primary
        natural_key:
            credential_type:
                kind: cloud
                name: generic credential 1
                type: credential_type
            name: Ascender Primary
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: cloud
            name: generic credential 2
            type: credential_type
        description: ''
        inputs:
            supp_gen2_user: admin
        name: Ascender Secondary
        natural_key:
            credential_type:
                kind: cloud
                name: generic credential 2
                type: credential_type
            name: Ascender Secondary
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: CIQ basics credential
        inputs:
            become_method: ''
            become_username: ''
            username: root
        name: basics-credential
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: basics-credential
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            username: admin
        name: Demo Credential
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Demo Credential
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: cloud
            name: SSH Certificate Key
            type: credential_type
        description: ''
        inputs: {}
        name: Greg SSH Private Key
        natural_key:
            credential_type:
                kind: cloud
                name: SSH Certificate Key
                type: credential_type
            name: Greg SSH Private Key
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            become_method: sudo
            become_username: ''
            username: root
        name: Lab Servers Root
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Lab Servers Root
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: cloud
            name: Mountain Access Key
            type: credential_type
        description: ''
        inputs: {}
        name: Mountain V2 Migration Key
        natural_key:
            credential_type:
                kind: cloud
                name: Mountain Access Key
                type: credential_type
            name: Mountain V2 Migration Key
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            become_method: ''
            become_username: ''
            username: admin
        name: Network Lab
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Network Lab
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: registry
            name: Container Registry
            type: credential_type
        description: ''
        inputs:
            host: registry.labs.io:5000
            username: root
            verify_ssl: false
        name: registry.labs.io
        natural_key:
            credential_type:
                kind: registry
                name: Container Registry
                type: credential_type
            name: registry.labs.io
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: cloud
            name: Mountain Access Key
            type: credential_type
        description: ''
        inputs: {}
        name: Rocky LTS Mixed Demo Mnt Key
        natural_key:
            credential_type:
                kind: cloud
                name: Mountain Access Key
                type: credential_type
            name: Rocky LTS Mixed Demo Mnt Key
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: cloud
            name: generic credential 1
            type: credential_type
        description: ''
        inputs:
            supp_gen1_user: administrator
        name: VMWare Server
        natural_key:
            credential_type:
                kind: cloud
                name: generic credential 1
                type: credential_type
            name: VMWare Server
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            become_method: ''
            become_username: ''
            username: administrator
        name: Windows administrator
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Windows administrator
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin


...
