

    inventory_sources:
    -   credential: null
        description: ''
        enabled_value: ''
        enabled_var: ''
        execution_environment: null
        host_filter: ''
        inventory:
            name: Dynamic custom inventory demo
            organization:
                name: Default
                type: organization
            type: inventory
        limit: ''
        name: Json parser
        natural_key:
            inventory:
                name: Dynamic custom inventory demo
                organization:
                    name: Default
                    type: organization
                type: inventory
            name: Json parser
            type: inventory_source
        overwrite: false
        overwrite_vars: false
        related:
            credentials: []
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
            schedules: []
        scm_branch: ''
        source: scm
        source_path: custom_inventory.py
        source_project:
            name: Dynamic custom inventory demo
            organization:
                name: Default
                type: organization
            type: project
        source_vars: ''
        timeout: 0
        update_cache_timeout: 0
        update_on_launch: false
        verbosity: 1


...
