

    projects:
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _6__demo_project
        name: Demo Project
        natural_key:
            name: Demo Project
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/ansible/ansible-tower-samples
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _8__rocky_lts_mixed_demo
        name: Rocky LTS Mixed Demo
        natural_key:
            name: Rocky LTS Mixed Demo
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ascender-rocky-lts
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _10__ascender_vmware
        name: Ascender VMWare
        natural_key:
            name: Ascender VMWare
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ascender-vmware
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _16__gregsowell_network_backup_git
        name: GregSowell Network Backup Git
        natural_key:
            name: GregSowell Network Backup Git
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/network_backup_git
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _17__gregsowell_network_cac
        name: GregSowell Network CAC
        natural_key:
            name: GregSowell Network CAC
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/cac-nexus
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _29__gregsowell_windows
        name: GregSowell Windows
        natural_key:
            name: GregSowell Windows
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ansible-windows
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _31__ansible_misc
        name: Ansible Misc
        natural_key:
            name: Ansible Misc
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ansible-misc
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: CIQ basics repository
        local_path: _34__basics_course
        name: basics-course
        natural_key:
            name: basics-course
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: true
        scm_url: https://github.com/gregsowell/ciq-basics/
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _35__greg_centos7_migration
        name: GregSowell centos7 migration
        natural_key:
            name: GregSowell centos7 migration
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ascender-centos7-to-rocky-elevate
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _46__ascender_cac_migration
        name: Ascender CAC Migration
        natural_key:
            name: Ascender CAC Migration
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ascender-configuration-as-code-migration
        signature_validation_credential: null
        timeout: 0
    -   allow_override: false
        credential: null
        default_environment: null
        description: ''
        local_path: _49__dynamic_custom_inventory_demo
        name: Dynamic custom inventory demo
        natural_key:
            name: Dynamic custom inventory demo
            organization:
                name: Default
                type: organization
            type: project
        organization:
            name: Default
            type: organization
        related:
            notification_templates_error: []
            notification_templates_started: []
            notification_templates_success: []
        scm_branch: ''
        scm_clean: false
        scm_delete_on_update: false
        scm_refspec: ''
        scm_track_submodules: false
        scm_type: git
        scm_update_cache_timeout: 0
        scm_update_on_launch: false
        scm_url: https://github.com/gregsowell/ascender-custom-dynamic-inventory-script.git
        signature_validation_credential: null
        timeout: 0


...
